In [4]:
import numpy as np
inputt = np.array([[-5,6]])
bias = -1.2
weight = np.array([[3],[2]])
print(inputt.shape)
print(weight.shape)

(1, 2)
(2, 1)


In [5]:
transf = np.dot(inputt,weight)
transfer = transf + bias
print(transfer)

[[-4.2]]


In [6]:
def linear(transfer):
    return transfer

In [7]:
linear(transfer)

array([[-4.2]])

In [8]:
def tanh(t):
    return np.tanh(t)

In [9]:
tanh(transfer)

array([[-0.99955037]])

In [12]:
def sigmoid(s):
        return 1/(1+np.exp(-s))

In [13]:
sigmoid(transfer)

array([[0.01477403]])