In [1]:
import numpy as np
x = np.array([[1,0.25,-0.5]])
y = np.array([[1,-1,0]])
print(x.shape)
#x.shape
print(y.shape)

(1, 3)
(1, 3)


In [36]:
class NeuralNetwork():
    def __init__(self):
        self.inputSize = 3
        self.outputSize = 3
        self.hiddenSize = 2

        self.w1 = np.random.randn(self.inputSize, self.hiddenSize)
        self.w2 = np.random.randn(self.hiddenSize, self.outputSize)

    def sigmoid(self,s):
        return 1/(1+np.exp(-s))
    def sigmoidder(self,s):
        return s*(1-s)

    def forward(self,x):
        self.z = np.dot(x, self.w1)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2, self.w2)
        o = self.sigmoid(self.z3)
        return o

    def backward(self,x,y,o):
        self.o_error = y-o
        self.o_delta = self.o_error*self.sigmoidder(o)

        self.z2_error = self.o_delta.dot(self.w2.T)
        self.z2_delta = self.z2_error*self.sigmoidder(self.z2)
        self.w1 += x.T.dot(self.z2_delta)
        self.w2 += self.z2.T.dot(self.o_delta)

    def train(self,x,y,num_train_iterations):
        for iteration in range(num_train_iterations):
            o = self.forward(x)
            self.backward(x,y,o)

In [38]:
if __name__ == "__main__":
    
    neural_network = NeuralNetwork()
    print("random weights at the start of the training")
    print(neural_network.w1)
    print(neural_network.w2)
    #neural_network.w1.shape
    neural_network.train(x,y,100)
    
    print("new weights after training ")
    print(neural_network.w1)
    print(neural_network.w2)
    
    print("testing network on a new example-->")
    print(neural_network.forward(np.array([[1,0.25,-0.5]])))
    
    

random weights at the start of the training
[[-0.87724645  1.0682017 ]
 [ 0.28088188 -0.31179814]
 [ 0.15809493 -1.61272487]]
[[ 0.83293653  0.3745967   1.06897052]
 [ 1.69690496  0.82587383 -0.5567276 ]]
new weights after training 
[[-0.61533301  2.0863534 ]
 [ 0.34636024 -0.05726021]
 [ 0.02713821 -2.12180072]]
[[ 1.0692231  -1.24123628  0.39991427]
 [ 2.43570514 -4.37894947 -2.68857647]]
testing network on a new example-->
[[0.93860512 0.00944868 0.08096931]]
