In [10]:
import numpy as np

In [11]:
x_train = np.array(([[0.2, 0.611, 0.682, 0.5, 0.529, 0.508],
              [0.2, 0, 0.536, 0.666, 0.576, 0.647],
              [0.1, 0, 0.329, 0.869, 0.711, 0.735],
              [0.3, 0, 0.756, 0.452, 0.491, 0.529],
              [0.5 ,0 ,0.585 ,0.619 ,0.627 ,0.852],
[0.2 ,0 ,0.524 ,0.678 ,0.576 ,0.676],
[0.5 ,0 ,0.573 ,0.63 ,0.61 ,0.823],
[0.2 ,0 ,0.512 ,0.69 ,0.576 ,0.647],
[0.1 ,0 ,0.341 ,0.857 ,0.694 ,0.705],
[0.2 ,0 ,0.548 ,0.654 ,0.576 ,0.647],
[0.7 ,0 ,0.353 ,0.845 ,0.677 ,1],
[0.5 ,0 ,0.585 ,0.619 ,0.61 ,0.823],
[0.2 ,0.222 ,0.682 ,0.476 ,0.508 ,0.529],
[0.1 ,0 ,0.317 ,0.88 ,0.728 ,0.764],
[0.1 ,0 ,0.341 ,0.857 ,0.711 ,0.735],
[0.2 ,0.166 ,0.67 ,0.50 ,0.525 ,0.558]]),dtype = float)
y_train = np.array(([[0.1],[0.292],[0.203],[0.129],[0.608],[0.328],
               [0.595],[0.296],[0.193],[0.289],[0.614],[0.594],
               [0.0842],[0.211],[0.21],[0.112]]),dtype=float)
print(x.shape)
#x.shape
print(y.shape)

(16, 6)
(16, 1)


In [12]:
class NeuralNetwork():
    def __init__(self):
        self.inputSize = 6
        self.outputSize = 1
        self.hiddenSize = 6

        self.w1 = np.random.randn(self.inputSize, self.hiddenSize)
        self.w2 = np.random.randn(self.hiddenSize, self.outputSize)

    def sigmoid(self,s):
        return 1/(1+np.exp(-s))
    def sigmoidder(self,s):
        return s*(1-s)

    def forward(self,x):
        self.z = np.dot(x, self.w1)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2, self.w2)
        o = self.sigmoid(self.z3)
        return o

    def backward(self,x,y,o):
        self.o_error = y-o
        self.o_delta = self.o_error*self.sigmoidder(o)

        self.z2_error = self.o_delta.dot(self.w2.T)
        self.z2_delta = self.z2_error*self.sigmoidder(self.z2)
        self.w1 += x.T.dot(self.z2_delta)
        self.w2 += self.z2.T.dot(self.o_delta)

    def train(self,x,y,num_train_iterations):
        for iteration in range(num_train_iterations):
            o = self.forward(x)
            self.backward(x,y,o)

In [15]:
if __name__ == "__main__":
    
    neural_network = NeuralNetwork()
    print("random weights at the start of the training")
    print(neural_network.w1)
    print(neural_network.w2)
    #neural_network.w1.shape
    neural_network.train(x_train,y_train,100)
    
    print("new weights after training ")
    print(neural_network.w1)
    print(neural_network.w2)
    
    x_test=np.array(([[0.1, 0, 0.304, 0.892, 0.728, 0.754],
[0.2, 0, 0.536, 0.666, 0.576, 0.647],
[0.5, 0, 0.597, 0.607, 0.61, 0.823],
[0.1, 0, 0.951, 0.261, 0.627, 0.676],
[0.2, 0, 0.512, 0.69, 0.593, 0.676],
[0.1, 0, 0.926, 0.285, 0.627, 0.676],
[0.2, 222, 0.658, 0.5, 0.525, 0.529],
[0.1, 0, 0.341, 0.857, 0.728, 0.735]]),dtype=float)
    print("\ntesting network on new example-->")
    print(neural_network.forward(x_test))

random weights at the start of the training
[[ 0.85007684  0.5758052  -0.57403343 -2.06628096  1.34129864  0.97297897]
 [-1.14911258  1.27485454 -0.00920871  0.12771145 -0.50431756  0.99723876]
 [-0.18096379  0.23956268 -0.38374731 -0.46024661 -0.72398897 -0.01216818]
 [-2.81601987  0.2243469  -0.34519962 -2.22848908  0.21442537 -0.81907706]
 [-0.06809625  0.1567361   0.18777779  0.97395725 -0.26994319 -0.13464741]
 [ 0.28404381  0.11907253  1.4660099   0.57742642 -0.07203948  0.18243271]]
[[ 0.31495065]
 [ 0.07976108]
 [-0.19902908]
 [ 0.09868212]
 [-1.11137772]
 [ 0.96439727]]
new weights after training 
[[ 1.5655492  -0.35379052 -1.34880394 -2.77202129  0.29922618  2.15877929]
 [-1.41976469  1.68958324  0.41600732  0.79524489  0.09259775  0.26130743]
 [-0.23766261  0.49366536 -0.08107399  0.5287687  -0.26673317 -0.73874553]
 [-2.42055192 -0.01388255 -0.49064142 -1.82641052  0.11361016 -0.79914203]
 [ 0.25541753 -0.01490692  0.10620179  1.43106976 -0.29426297 -0.21299996]
 [ 1.073980