In [10]:
import numpy as np
x = np.array([[0,0,0,0],[0,0,0,1],[0,0,1,0],[0,0,1,1],[0,1,0,0],[0,1,1,0],[0,1,0,1],[0,1,1,1],
              [1,0,0,0],[1,0,0,1],[1,0,1,0],[1,0,1,1],[1,1,0,0],[1,1,1,0],[1,1,0,1],[1,1,1,1]])
y = np.array([[0],[1],[1],[0],[1],[0],[0],[1],
              [1],[0],[0],[1],[0],[1],[1],[0]])
print(x.shape)
#x.shape
print(y.shape)

(16, 4)
(16, 1)


In [11]:
class NeuralNetwork():
    def __init__(self):
        self.inputSize = 4
        self.outputSize = 1
        self.hiddenSize = 4

        self.w1 = np.random.uniform(-1,1,size=(self.inputSize, self.hiddenSize))
        self.w2 = np.random.uniform(-1,1,size=(self.hiddenSize, self.outputSize))

    def sigmoid(self,s):
        return 1/(1+np.exp(-s))
    def sigmoidder(self,s):
        return s*(1-s)

    def forward(self,x):
        self.z = np.dot(x, self.w1)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2, self.w2)
        o = self.sigmoid(self.z3)
        return o

    def backward(self,x,y,o):
        self.o_error = y-o
        self.o_delta = self.o_error*self.sigmoidder(o)

        self.z2_error = self.o_delta.dot(self.w2.T)
        self.z2_delta = self.z2_error*self.sigmoidder(self.z2)
        self.w1 += x.T.dot(self.z2_delta)
        self.w2 += self.z2.T.dot(self.o_delta)

    def check(self,a1,a2):
        a=abs(a1-a2)
        print(a)
        for i in a:
            if i>0.1:
                return False
        return True    
    def train(self,inputs,output):
        o=self.forward(inputs)
        booll=self.check(output,o)
        if booll==True:
            return 1
        else:
            self.backward(inputs,output,o)
            return -1        
   

In [17]:
if __name__ == "__main__":
    
    neural_network = NeuralNetwork()
    print("random weights at the start of the training")
    print(neural_network.w1)
    print(neural_network.w2)
    #neural_network.w1.shape
    parity=-1
    it=0
    while(parity==-1 and it<7000):
        parity=neural_network.train(x,y)
        it=it+1

    print('New weights after training')
    print(neural_network.w1)
    print(neural_network.w2)
    
    out=neural_network.forward(x)
    for i in out:
        if i<0.5:
            i=0
            print(i)
        else:
            i=1
            print(i)
     

random weights at the start of the training
[[ 0.11451499  0.03903855 -0.44922839  0.96522361]
 [ 0.2706061  -0.92502731  0.90273274  0.40683378]
 [-0.54981154  0.35511538  0.08536286 -0.75426743]
 [-0.44272859  0.19444461  0.13580152  0.53481984]]
[[ 0.42562875]
 [-0.63069801]
 [-0.37475507]
 [-0.46880423]]
[[0.37184397]
 [0.66265856]
 [0.63653503]
 [0.33146012]
 [0.61909799]
 [0.37478962]
 [0.3487519 ]
 [0.65854079]
 [0.64152593]
 [0.32842148]
 [0.34928467]
 [0.6823689 ]
 [0.36959535]
 [0.64095046]
 [0.65768363]
 [0.32799251]]
[[0.51131494]
 [0.51318495]
 [0.51139115]
 [0.46634346]
 [0.46170855]
 [0.51659214]
 [0.51470614]
 [0.5070028 ]
 [0.48776505]
 [0.48863144]
 [0.48906119]
 [0.53397721]
 [0.53959116]
 [0.48305746]
 [0.48255078]
 [0.49339391]]
[[0.50814466]
 [0.51621202]
 [0.51364406]
 [0.46419426]
 [0.46629457]
 [0.51291208]
 [0.51025954]
 [0.51054174]
 [0.49123583]
 [0.48537777]
 [0.4865058 ]
 [0.53641172]
 [0.5347438 ]
 [0.48709157]
 [0.48719737]
 [0.48953153]]
[[0.50861402]
 