In [1]:
import numpy as np
x = np.array(([2,9], [1,5], [3,6] ),dtype = float)
y = np.array(([92],[86],[89]),dtype = float)
print(x.shape)
print(y.shape)
x = x/np.amax(x, axis = 0)
y = y/100


(3, 2)
(3, 1)


In [9]:
class NeuralNetwork():
    def __init__(self):
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3

        self.w1 = np.random.randn(self.inputSize, self.hiddenSize)
        self.w2 = np.random.randn(self.hiddenSize, self.outputSize)

    def sigmoid(self,s):
        return 1/(1+np.exp(-s))
    def sigmoidder(self,s):
        return s*(1-s)

    def forward(self,x):
        self.z = np.dot(x, self.w1)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2, self.w2)
        o = self.sigmoid(self.z3)
        return o

    def backward(self,x,y,o):
        self.o_error = y-o
        self.o_delta = self.o_error*self.sigmoidder(o)

        self.z2_error = self.o_delta.dot(self.w2.T)
        self.z2_delta = self.z2_error*self.sigmoidder(self.z2)

        self.w1 += x.T.dot(self.z2_delta)
        self.w2 += self.z2.T.dot(self.o_delta)

    def train(self,x,y,num_train_iterations):
        for iteration in range(num_train_iterations):
            o = self.forward(x)
            self.backward(x,y,o)

In [11]:
if __name__ == "__main__":
    
    neural_network = NeuralNetwork()
    print("random weights at the start of the training")
    print(neural_network.w1)
    print(neural_network.w2)
    
    neural_network.train(x,y,10000)
    
    print("new weights after training ")
    print(neural_network.w1)
    print(neural_network.w2)
    
    print("testing network on a new example-->")
    print(neural_network.forward(np.array([0,1])))
    
    

random weights at the start of the training
[[ 1.45719532 -2.00051782 -0.6489318 ]
 [ 0.94006363 -1.43109179  1.46522632]]
[[-1.63577623]
 [-0.96623514]
 [ 2.32901357]]
new weights after training 
[[ 1.3041963  -1.95008356 -0.04645528]
 [ 0.80052888 -1.29204852  1.84639718]]
[[-0.41809999]
 [-1.51690676]
 [ 3.32096253]]
testing network on a new example-->
[0.90490026]
