In [23]:
import numpy as np
from numpy import exp,array,random,dot,tanh

In [24]:
class NeuralNetwork():
    def __init__(self):
        random.seed(1)
        self.weight_matrix = 2*random.random((3,1)) - 1
    def tanh(self,x):
        return tanh(x)
    def tanh_derivative(self,x):
        return 1.0-tanh(x)**2
    def forward_propagation(self,inputs):
        return self.tanh(dot(inputs,self.weight_matrix))
    def train(self,train_inputs,train_outputs,num_train_iterations):
        for iteration in range(num_train_iterations):
            output = self.forward_propagation(train_inputs)
            error = train_outputs-output
            
            adjustment = dot(train_inputs.T,error*self.tanh_derivative(output))
            self.weight_matrix+= adjustment
if __name__ == "__main__":
    
    neural_network = NeuralNetwork()
    
    print("random weights at the start of the training")
    print(neural_network.weight_matrix)
    
    train_inputs = array([[0,0,1], [1,1,1], [1,0,1], [0,1,1]])
    train_outputs = array([[0,1,1,0]]).T
    
    neural_network.train(train_inputs,train_outputs,10000)
    
    print("new weights after training ")
    print(neural_network.weight_matrix)
    
    print("testing network on a new example-->")
    print(neural_network.forward_propagation(array([0,1,0])))
    
            

random weights at the start of the training
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
new weights after training 
[[5.39428067]
 [0.19482422]
 [0.34317086]]
testing network on a new example-->
[0.19239613]


In [25]:
class NeuralNetwork():
    def __init__(self):
        random.seed(1)
        self.weight_matrix = 2*random.random((3,1)) - 1
    def sigmoid(self,x):
        return  1. / (1. + np.exp(-x))
    def sigmoid_derivative(self,x):
        return np.exp(-x)/ (1. + np.exp(-x))
    def forward_propagation(self,inputs):
        return self.sigmoid(dot(inputs,self.weight_matrix))
    def train(self,train_inputs,train_outputs,num_train_iterations):
        for iteration in range(num_train_iterations):
            output = self.forward_propagation(train_inputs)
            error = train_outputs-output
            
            adjustment = dot(train_inputs.T,error*self.sigmoid_derivative(output))
            self.weight_matrix+= adjustment
if __name__ == "__main__":
    
    neural_network = NeuralNetwork()
    
    print("random weights at the start of the training")
    print(neural_network.weight_matrix)
    
    train_inputs = array([[0,0,1], [1,1,1], [1,0,1], [0,1,1]])
    train_outputs = array([[0,1,1,0]]).T
    
    neural_network.train(train_inputs,train_outputs,10000)
    
    print("new weights after training ")
    print(neural_network.weight_matrix)
    
    print("testing network on a new example-->")
    print(neural_network.forward_propagation(array([0,1,0])))
    
            

random weights at the start of the training
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
new weights after training 
[[16.04635503]
 [-0.4061331 ]
 [-7.9271745 ]]
testing network on a new example-->
[0.39983969]
